# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MockupTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MockupTest

  target 'MockupTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MockupTestUITests' do
    # Pods for testing
  end

end
