# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MockupTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Toast'
  pod 'GoogleSignIn'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        config.build_settings['CODE_SIGN_IDENTITY[sdk=iphoneos*]'] = ''
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  end

  # Pods for MockupTest

  target 'MockupTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MockupTestUITests' do
    # Pods for testing
  end

end
